console.log(Math.ceil(10.1))//ye khich kar upar ki taraf le jayega 10.something hai to usse 11 bana dega aise hi kuch bhi point something 
//ho to usse uper value me le jayega

//iska opposite floor
console.log(Math.floor(10.6))//ye niche ki taraf layega floor means niche means 10.something = 10

//combination of ceil and floor
console.log(Math.round(10.5))//agar .5 ya uss se upar ka value liya hai to it behave like ceil agar uss se kam hai to behave like
//floor ex. = 10.3 = 10 , 10.5 = 11
console.log(Math.abs(-5))//negative value ko positive me change karega positive ka positive me hi rhne dega

console.log(Math.trunc(10.287934973497))//ye decimal ke baad ke saare value ko hata dega
console.log(Math.pow(5,2)) //pow means power 5 ki power 2 sabse pahle exponent then power aur uska solution dega i.e. 25 

console.log(Math.sqrt(36))// 36 kiska square root hai 6 ka to it returns 6 but what if i take 40 , 
console.log(Math.sqrt(40))//it returns in point
//for cube root
console.log(Math.cbrt(125))

console.log(Math.max(10,67,90,32))///it returns maximum value
console.log(Math.min(10,39,32,4))

console.log(Math.random())// 0 se lekar 1 ke bich me humesa ek random value dega
